In [26]:
import numpy as np 
import pandas as pd

In [27]:
train=pd.read_csv('input/sample-data/train_preprocessed_onehot.csv')
train_x=train.drop(['target'], axis = 1)
train_y=train['target']
test_x = pd.read_csv('input/sample-data/test_preprocessed_onehot.csv')

In [28]:
train_x

,age,sex,height,weight,product_0,product_1,product_2,product_3,product_4,product_5,...,medical_keyword_7,medical_keyword_8,medical_keyword_9,medical_keyword_10,year,month,day,yearmonth,medical_info_c1_nan,medical_info_c2_nan
0,50,1,166.445608,65.016732,0,0,0,0,0,0,...,0,1,0,0,2015,2,3,24182,False,True
1,68,0,164.334615,56.544217,1,0,0,0,0,0,...,1,1,0,0,2015,5,9,24185,True,True
2,77,1,167.462917,54.242267,0,0,1,0,0,0,...,0,1,0,0,2016,2,13,24194,False,True
3,17,1,177.097725,71.147762,0,0,0,1,0,0,...,0,1,0,0,2015,7,6,24187,False,False
4,62,0,158.165788,65.240697,0,1,0,0,0,0,...,1,1,1,0,2016,9,17,24201,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,61,1,182.729800,73.393777,0,1,0,0,0,0,...,0,1,1,0,2015,10,21,24190,False,True
9996,33,0,167.701136,75.006529,0,0,0,0,0,0,...,0,1,1,0,2015,5,28,24185,False,True
9997,44,0,145.609998,47.739397,0,0,0,0,0,0,...,0,1,0,1,2016,2,29,24194,True,True
9998,34,0,165.796017,57.567695,0,0,0,0,0,0,...,1,1,1,0,2016,2,27,24194,False,True
9999,31,1,180.301762,71.425135,0,0,0,0,1,0,...,0,1,0,0,2015,7,1,24187,False,False

In [29]:
#학습 데이터와 검증 데이터 구분
from sklearn.model_selection import KFold
kf = KFold(n_splits= 4, shuffle= True, random_state=71)
tr_idx, va_idx = list(kf.split(train_x))[0]
tr_x, va_x = train_x.iloc[tr_idx], train_x.iloc[va_idx]
tr_y, va_y = train_y.iloc[tr_idx], train_x.iloc[va_idx]

In [30]:
#경고 억제
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='1'
import tensorflow as tf 
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)

In [31]:
#NN with keras
from keras.layers import Dense, Dropout 
from keras.models import Sequential 
from sklearn.metrics import log_loss
from sklearn.preprocessing import StandardScaler

In [32]:
#data scaling
scaler = StandardScaler()
tr_x= scaler.fit_transform(tr_x)
va_x= scaler.transform(va_x)
test_x = scaler.transform(test_x)

In [33]:
# #modeling nn
# model= Sequential()
# model.add(Dense(256, activation='relu', input_shape= (train_x.shape[1],))) 
# #train_x.shape[1] 은 열의 개수, 열벡터의 transpose를 input으로 받아야 하니까 이렇게 설정함
# model.add(Dropout(0.2))
# model.add(Dense(256, activation = 'relu'))
# model.add(Dropout(0.2))
# model.add(Dense(1, activation= 'sigmoid'))

# model.compile(loss='binary_crossentropy', optimizer='adam', metrics =['accuracy'])

In [34]:
# #training
# batch_size= 128
# epochs= 10 
# history = model.fit(tr_x, tr_y, batch_size= batch_size, epochs = epochs, verbose= 1,
#                     validation_data=(va_x, va_y))

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss
from sklearn.preprocessing import StandardScaler

In [36]:
scaler = StandardScaler()
tr_x = scaler.fit_transform(tr_x)
va_x = scaler.transform(va_x)
test_x= scaler.transform(test_x)

In [43]:
#training
model = LogisticRegression(C=1.0)
model.fit(tr_x, tr_y)

LogisticRegression()

In [45]:
va_pred=model.predict_proba(va_x)
score = log_loss(va_y, va_pred)

ValueError: Unknown label type: (      age  sex      height     weight  product_0  product_1  product_2  \
6      63    1  181.146801  63.982878          0          0          1
10     54    1  175.576514  52.470671          0          0          0
11     17    0  162.283723  51.544568          0          0          0
12      5    1  160.458369  55.488517          0          0          0
23     35    0  147.256907  44.591515          0          0          1
...   ...  ...         ...        ...        ...        ...        ...
9986   56    1  164.690874  49.944398          0          0          0
9988   78    1  163.731638  62.836367          0          0          1
9994   73    1  176.562011  66.131343          1          0          0
9995   61    1  182.729800  73.393777          0          1          0
9997   44    0  145.609998  47.739397          0          0          0

      product_3  product_4  product_5  ...  medical_keyword_7  \
6             0          0          0  ...                  0
10            0          0          0  ...                  0
11            0          0          0  ...                  1
12            0          1          0  ...                  0
23            0          0          0  ...                  1
...         ...        ...        ...  ...                ...
9986          0          0          0  ...                  1
9988          0          0          0  ...                  1
9994          0          0          0  ...                  0
9995          0          0          0  ...                  0
9997          0          0          0  ...                  0

      medical_keyword_8  medical_keyword_9  medical_keyword_10  year  month  \
6                     0                  1                   0  2015      8
10                    1                  0                   0  2016     12
11                    1                  0                   0  2016      2
12                    1                  0                   0  2016      8
23                    1                  0                   0  2015     12
...                 ...                ...                 ...   ...    ...
9986                  1                  0                   0  2016      7
9988                  0                  0                   0  2015      9
9994                  1                  1                   0  2016      6
9995                  1                  1                   0  2015     10
9997                  1                  0                   1  2016      2

      day  yearmonth  medical_info_c1_nan  medical_info_c2_nan
6      19      24188                False                 True
10     24      24204                False                 True
11     28      24194                False                 True
12     20      24200                False                 True
23     15      24192                False                 True
...   ...        ...                  ...                  ...
9986   27      24199                False                False
9988    5      24189                False                 True
9994   19      24198                False                 True
9995   21      24190                False                 True
9997   29      24194                 True                 True

[2500 rows x 59 columns],)